name: KotlinDemo
main: de.dustplanet.kotlindemo.KotlinDemo
version: 0.0.1
author: xGhOsTkiLLeRx
website: https://github.com/timbru31/bukkit-kotlin-demo
api-version: 1.13
commands:
  kotlin:
    description: Greets all online players
    usage: /kotlin - unleashes the Kotlin power!
